// <auto-generated />
using System;
using BunkerMVP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BunkerMVP.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BunkerDbContext))]
    [Migration("20260309053050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BunkerMVP.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$aQqFSwkbtyVU0muddz2zdupUDHYJvFqafKC27g3yr.9EMhVZAAGjm",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.BunkerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BunkerRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierQuoteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BunkerRequestId")
                        .IsUnique();

                    b.HasIndex("SupplierQuoteId")
                        .IsUnique();

                    b.ToTable("BunkerOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BunkerRequestId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Notes = "Order confirmed",
                            OrderDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            SupplierQuoteId = 3,
                            TotalAmount = 483750m
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.BunkerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ETA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VesselId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VesselId");

                    b.ToTable("BunkerRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETA = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            ProductId = 1,
                            Quantity = 500m,
                            Status = "Quoted",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VesselId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETA = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            ProductId = 2,
                            Quantity = 200m,
                            Status = "Open",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VesselId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETA = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 3,
                            ProductId = 3,
                            Quantity = 750m,
                            Status = "Ordered",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VesselId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETA = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            ProductId = 2,
                            Quantity = 300m,
                            Status = "Draft",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VesselId = 1
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Singapore",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Singapore Port",
                            Port = "Singapore"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rotterdam Port",
                            Port = "Rotterdam"
                        },
                        new
                        {
                            Id = 3,
                            Country = "UAE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fujairah Port",
                            Port = "Fujairah"
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Very Low Sulphur Fuel Oil",
                            Name = "VLSFO",
                            ProductCode = "VLSFO-380",
                            Unit = "MT"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Marine Gas Oil",
                            Name = "MGO",
                            ProductCode = "MGO-DMA",
                            Unit = "MT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High Sulphur Fuel Oil",
                            Name = "HSFO",
                            ProductCode = "HSFO-380",
                            Unit = "MT"
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactEmail = "ops@oceanfuel.sg",
                            ContactPhone = "+6561234567",
                            Country = "Singapore",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "OceanFuel Pte Ltd"
                        },
                        new
                        {
                            Id = 2,
                            ContactEmail = "ops@euromarine.nl",
                            ContactPhone = "+31101234567",
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "EuroMarine Fuels BV"
                        },
                        new
                        {
                            Id = 3,
                            ContactEmail = "ops@gulfbunkers.ae",
                            ContactPhone = "+97141234567",
                            Country = "UAE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gulf Bunkers LLC"
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.SupplierQuote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BunkerRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BunkerRequestId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierQuotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BunkerRequestId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Notes = "Price includes delivery",
                            Price = 620m,
                            SupplierId = 1,
                            ValidUntil = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BunkerRequestId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Notes = "Best price guaranteed",
                            Price = 615m,
                            SupplierId = 2,
                            ValidUntil = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BunkerRequestId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Notes = "Fujairah ex-wharf",
                            Price = 645m,
                            SupplierId = 3,
                            ValidUntil = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMONumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IMONumber")
                        .IsUnique();

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Flag = "Panama",
                            IMONumber = "IMO9234567",
                            Name = "MV Pacific Star",
                            VesselType = "Bulk Carrier"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Flag = "Marshall Islands",
                            IMONumber = "IMO9345678",
                            Name = "MV Atlantic Crown",
                            VesselType = "Tanker"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Flag = "Liberia",
                            IMONumber = "IMO9456789",
                            Name = "MV Indian Breeze",
                            VesselType = "Container"
                        });
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.BunkerOrder", b =>
                {
                    b.HasOne("BunkerMVP.Domain.Entities.BunkerRequest", "BunkerRequest")
                        .WithOne("BunkerOrder")
                        .HasForeignKey("BunkerMVP.Domain.Entities.BunkerOrder", "BunkerRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BunkerMVP.Domain.Entities.SupplierQuote", "SupplierQuote")
                        .WithOne("BunkerOrder")
                        .HasForeignKey("BunkerMVP.Domain.Entities.BunkerOrder", "SupplierQuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BunkerRequest");

                    b.Navigation("SupplierQuote");
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.BunkerRequest", b =>
                {
                    b.HasOne("BunkerMVP.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BunkerMVP.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BunkerMVP.Domain.Entities.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.SupplierQuote", b =>
                {
                    b.HasOne("BunkerMVP.Domain.Entities.BunkerRequest", "BunkerRequest")
                        .WithMany("SupplierQuotes")
                        .HasForeignKey("BunkerRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BunkerMVP.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BunkerRequest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.BunkerRequest", b =>
                {
                    b.Navigation("BunkerOrder");

                    b.Navigation("SupplierQuotes");
                });

            modelBuilder.Entity("BunkerMVP.Domain.Entities.SupplierQuote", b =>
                {
                    b.Navigation("BunkerOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
